### ISSUE TITLE
Getting error in "make command"

### ISSUE THREAD

**Issue by Dhara-Openxcell** [riecoin/riecoin#11]
Hello,
I am working on ubuntu system 16.04 

After cloning the repository from master branch I tried below commands:

```
1.   ./autogen.sh
2.  ./configure
3.  make
```

On firing "make " command I am getting below error: 

```
In file included from chainparams.h:9:0,
                 from util.cpp:8:
bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:13,
                 from chainparams.h:9,
                 from util.cpp:8:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~

Makefile:2658: recipe for target 'libbitcoin_util_a-util.o' failed
make[2]: *** [libbitcoin_util_a-util.o] Error 1
make[2]: Leaving directory '/root/riecoin/clams/src'
Makefile:4215: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/riecoin/clams/src'
Makefile:558: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Does anyone have any idea regarding to this?
